# Generated by Django 6.1 on 2026-09-11 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesheet_board', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesheet',
            name='path',
            field=models.CharField(default='notesheet/', max_length=64),
        ),
    ]
