# Generated by Django 6.1 on 2026-09-12 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notesheet_board', '0002_notesheet_path'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notesheet',
            old_name='path',
            new_name='file_name',
        ),
    ]
