# Generated by Django 6.1 on 2026-09-12 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesheet_board', '0003_rename_path_notesheet_file_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesheet',
            name='quarter',
            field=models.CharField(default='Autumn', max_length=8),
        ),
        migrations.AddField(
            model_name='notesheet',
            name='year',
            field=models.PositiveSmallIntegerField(default=2026),
        ),
    ]
