# Generated by Django 6.1 on 2026-09-12 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesheet_board', '0004_notesheet_quarter_notesheet_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='notesheet',
            name='saved_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
