# Generated by Django 6.1 on 2026-09-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notesheet_board', '0006_notesheet_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notesheet',
            name='file_name',
        ),
        migrations.AddField(
            model_name='notesheet',
            name='note_pages',
            field=models.JSONField(default=['a.jpeg']),
            preserve_default=False,
        ),
    ]
