// Generated by django-typescript-api
// DO NOT EDIT THIS FILE DIRECTLY

/* eslint-disable */
// @ts-nocheck

/**
 * notesheet
 * Plural: notesheets
 *
 * Notesheet(id, title, description, file_name, year, quarter, saved_count, author)
 *
 * @interface Notesheet
 */
export interface Notesheet {
  /**
   * @maxLength 64
   */
  title: string;
  /**
   * @maxLength 500
   */
  description: string;
  /**
   * @maxLength 64
   * @default notesheet/
   */
  file_name: string;
  year: number;
  /**
   * @maxLength 8
   * @default Autumn
   */
  quarter: string;
  saved_count: number;
  author: User | number;
}
